repo_url: https://github.com/Requisitos-de-Software/2024.1-Correios
repo_name: 2024.1-Correios
site_name: Correios
nav: 
  - Equipe: index.md
  - Apresentações:
    - Apresentação 01: Apresentações/Apresentação_01.md
    - Apresentação 02: Apresentações/Apresentação_02.md
    - Apresentação 03: Apresentações/Apresentação_03.md
    - Apresentação 04: Apresentações/Apresentação_04.md
    - Apresentação 05: Apresentações/Apresentação_05.md
    - Apresentação 06: Apresentações/Apresentação_06.md
    - Apresentação 07: Apresentações/Apresentação_07.md
  - Atas:
    - Reunião 1: atas/ata1.md
    - Reunião 2: atas/ata2.md
    - Reunião 3: atas/ata3.md
    - Reunião 4: atas/ata4.md
    - Reunião 5: atas/ata5.md
    - Reunião 6: atas/ata6.md
    - Reunião 7: atas/ata7.md
  - Pré-Rastreabilidade:
    - Rich Picture: pre-rastreabilidade/richpicture.md
    - Aplicativos Avaliados: pre-rastreabilidade/appsavaliados.md
  - Planejamento:
    - Aplicativo escolhido: planejamento/aplicativoEscolhido.md
    - Heatmap: planejamento/heatmap.md
    - Cronograma:  planejamento/cronograma.md
    - Termo de Uso: planejamento/termodeuso.md
    - Ferramentas: planejamento/ferramentas.md
  - Elicitação:
    - Perfil de Usuário: elicitacao/perfil_de_usuario/perfil_de_usuario.md
    - Personas: elicitacao/personas.md
    - Técnicas:
      - Análise Documental: elicitacao/tecnicas/analise-documental.md
      - Brainstorming: elicitacao/tecnicas/brainstorming.md
      - Observação: elicitacao/tecnicas/observacao.md
      - Questionário: elicitacao/tecnicas/questionario.md
    - Priorização: 
      - $100: priorizacao/tecnicas/$100.md
      - First Things First: priorizacao/tecnicas/firstThingsFirst.md
      - In Or Out: priorizacao/tecnicas/inorout.md
    - Requisitos Elicitados: "elicitacao/requisitos_elicitados.md"
  - Modelagem:
    - Cenários: modelagem/cenarios.md
    - Casos de Uso: modelagem/casos_de_uso.md
    - Validação dos Casos de Uso: modelagem/validacao.md
    - Especificação Suplementar: modelagem/especificacao_suplementar.md
    - Léxicos: modelagem/lexicos.md
    - Ágil:
      - Backlog: modelagem/agil/backlog.md
      - Histórias de Usuário: modelagem/agil/historias_de_usuario.md
      - NFR Framework: modelagem/agil/nfr-framework.md
  - Verificação:
    - Grupo + 1:
      - Elicitação:
        - Perfil de Usuario: verificacao/grupo+1/elicitacao/perfil_do_usuario.md
        - Termo de Consentimento: verificacao/grupo+1/elicitacao/tdu_perfil.md
        - Personas: verificacao/grupo+1/elicitacao/personas.md
        - Elicitação:
          - Termo de Consentimento: verificacao/grupo+1/elicitacao/tdu_priorizacao.md
          - Análise de Documentos: verificacao/grupo+1/elicitacao/analise-documentos.md
          - Storytelling: verificacao/grupo+1/elicitacao/storytelling.md 
          - Brainstorming: verificacao/grupo+1/elicitacao/brainstorming.md
          - Requisitos Elicitados: verificacao/grupo+1/elicitacao/requisitos_elicitados.md          
        - Priorização:
          - First Things First: verificacao/grupo+1/elicitacao/firstThingsFirst.md
          - MoSCoW: verificacao/grupo+1/elicitacao/moscow.md
          - Three Level Scale: verificacao/grupo+1/elicitacao/threelevelscale.md
      - Modelagem:
        - Cenários: verificacao/grupo+1/modelagem/cenarios.md
        - Casos de Uso: verificacao/grupo+1/modelagem/casodeuso.md
        - Especificação Suplementar: verificacao/grupo+1/modelagem/especificacao_suplementar.md
        - Léxicos: verificacao/grupo+1/modelagem/Léxicos.md
        - Ágil:
          - Backlog: verificacao/grupo+1/modelagem/agil/backlog.md
          - Histórias de Usuário: verificacao/grupo+1/modelagem/agil/historias_de_usuario.md
          - NFR Framework: verificacao/grupo+1/modelagem/agil/nfrframework.md
    - Grupo:
      - Planejamento Geral:  verificacao/grupo/planejamento_geral.md
      - Pré-Rastreabilidade:
        - Planejamento da Verificação: verificacao/grupo/pre-rastreabilidade/planejamento_04.md
        - Rich Picture: verificacao/grupo/pre-rastreabilidade/richpicture.md
      - Elicitação:
        - Planejamento da Verificação: verificacao/grupo/elicitacao/planejamento_01.md
        - Perfil de Usuário: verificacao/grupo/elicitacao/perfil_usuario.md
        - Personas: verificacao/grupo/elicitacao/personas.md
        - Técnicas:
          - Análise Documental: verificacao/grupo/elicitacao/tecnicas/analise-documental.md
          - Brainstorming: verificacao/grupo/elicitacao/tecnicas/brainstorming.md
          - Observação: verificacao/grupo/elicitacao/tecnicas/observacao.md
          - Questionário: verificacao/grupo/elicitacao/tecnicas/quest.md
        - Priorização: 
          - $100: verificacao/grupo/elicitacao/priorizacao/100usd.md
          - First Things First: verificacao/grupo/elicitacao/priorizacao/firstthingfirst.md
          - In Or Out: verificacao/grupo/elicitacao/priorizacao/in_or_out.md
      - Modelagem:
        - Planejamento da Verificação: verificacao/grupo/modelagem/planejamento_02.md
        - Cenários: verificacao/grupo/modelagem/cenarios.md
        - Casos de Uso: 
          - Calcular preços e prazos de entrega: verificacao/grupo/modelagem/casos_de_uso/Calcular_precos_e_orazos.md
          - Relaizar compras na loja online: verificacao/grupo/modelagem/casos_de_uso/Realizar_compras.md
          - Mudar locais de recebimento de pacotes: verificacao/grupo/modelagem/casos_de_uso/Muda_locais.md
          - Relizar pré-postagem: verificacao/grupo/modelagem/casos_de_uso/Pre_postagem.md
          - Gerenciar minhas importações: verificacao/grupo/modelagem/casos_de_uso/Minhas_importacoes.md
          - Rastrear encomendas: verificacao/grupo/modelagem/casos_de_uso/Rastrear_encomendas.md
          - Buscar por documentos perdidos: verificacao/grupo/modelagem/casos_de_uso/Busca_por_documentos.md
        - Especificação Suplementar: verificacao/grupo/modelagem/especificacao_suplementar.md
        - Léxicos: verificacao/grupo/modelagem/lexicos.md
        - Ágil:
          - Backlog: verificacao/grupo/modelagem/agil/backlog.md
          - Histórias de Usuário: verificacao/grupo/modelagem/agil/historias_de_usuario.md
          - NFR Framework: verificacao/grupo/modelagem/agil/nfr.md
      - Pós-Rastreabilidade:
        - Planejamento da Verificação: verificacao/grupo/pos-rastreabilidade/planejamento_03.md
        - Backward-From: verificacao/grupo/pos-rastreabilidade/backward-from.md
        - Forward-From: verificacao/grupo/pos-rastreabilidade/forward-from.md
        - Matriz de Rastreabilidade: verificacao/grupo/pos-rastreabilidade/matriz.md
  - Validação:
    - Loja Online: validacao/loja_online.md 
    - Chatbot para suporte : validacao/chatbot.md
    - Minhas importações: validacao/importacoes.md
    - Adicionar endereços cadastrados em uma pré-postagem: validacao/pre-postagem.md
    - Visualizar encomenda no mapa: validacao/rastreamento-mapa.md
    - Mudar recebimento: validacao/muda-recebimento.md
    - Chat Fornecedor/Entregador: validacao/chats_for_ent.md
    - Comprovação informal: validacao/comprovacao-informal.md
  - Pós-Rastreabilidade:
    - Backward-From: pos-rastreabilidade/backward-from.md
    - Forward-From: pos-rastreabilidade/forward-from.md
    - Matriz de Rastreabilidade: pos-rastreabilidade/matriz.md
  

extra_css:
  - stylesheets/extra.css
theme:
  language: pt-BR
  name: material
  favicon: assets/correios_icon.svg
  logo: assets/correios-icon-black.svg
  features:
    - navigation.tabs
    - navigation.top
    - content.tabs.link
  palette:
    - scheme : default
      primary: amber
      accent: custom
      toggle:
        icon: material/toggle-switch
        name: Mudar o modo clar/escuro 

    - scheme: slate
      primary: amber
      accent: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mudar o modo clar/escuro
extra:
  analytics:
    provider: google
    property: G-41DM9F5YEC

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

